# Generated by Django 4.1 on 2022-08-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eid", models.CharField(max_length=50)),
                ("ename", models.CharField(max_length=50)),
                ("econtact", models.CharField(max_length=50)),
            ],
        ),
    ]
